### ISSUE TITLE
Implementation versions for ChainX

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate-telemetry#105]
When I view the ChainX tabs in Telemetry, the "Implementation" version tabs have values as shown in below screenshots (i.e. `?` or `? CARGO_PKG....`):

<img width="821" alt="screen shot 2019-02-03 at 1 08 40 pm" src="https://user-images.githubusercontent.com/6226175/52171674-19fbb180-27b5-11e9-86c4-c18b54901a6c.png">

<img width="619" alt="screen shot 2019-02-03 at 1 08 14 pm" src="https://user-images.githubusercontent.com/6226175/52171676-1e27cf00-27b5-11e9-8ce0-7495e218480c.png">

**Comment by maciejhirsz** [comment]
I've seen that, telemetry can't parse the version number it's being provided so it just puts it verbatim as it gets it from the node. I'm not sure whether anything needs to change here, since the onus is rather on the nodes to provide a valid version numbers.

Alternatively I could just print a `?` for the version number itself when it can't parse semver at all.
