### ISSUE TITLE
Update Readme to show how to easily setup a Substrate node

### ISSUE THREAD

**Issue by ltfschoen** [paritytech/substrate-telemetry#140]
The instructions https://github.com/paritytech/substrate-telemetry#terminal-3---node currently only say you can run a node with:
```
./target/debug/polkadot --dev --telemetry-url ws://localhost:1024
```

But it doesn't mention that you can also now run it with the prefix of `./target/debug/substrate --dev` when building it from source.

I think it should instead show that now you can easily get Substrate with `curl https://getsubstrate.io -sSf | bash` as mentioned here https://docs.substrate.dev/, and then also just run it with the binary `substrate --dev`.

**Comment by chevdor** [comment]
Hi @ltfschoen,

I am revisiting this issue and I see the doc evolved in the meantime. Is it acceptable now and we close this issue or do you think we should provide more details ?

**Comment by ltfschoen** [comment]
we've got established 

* for the [Polkadot repo](https://github.com/paritytech/polkadot) it now mentions [here](https://github.com/paritytech/polkadot#hacking-on-polkadot) how to easily get Substrate from getsubstrate.io, and it shows that [here](https://github.com/paritytech/polkadot#networks) that you don't need to specify anything for `--telemetry-url` in order for your node to appear at telemetry.polkadot.io when you run `./target/release/polkadot --chain=...`, since it's done automatically 

* for other Substrate-based chains, the [Substrate repo](https://github.com/paritytech/substrate) already provides a link to substrate.dev, and at those docs it already shows [here](https://substrate.dev/docs/en/knowledgebase/getting-started/) how to easily get Substrate from getsubstrate.io.  It also already shows [here](https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain) in the "Start a Private Network" tutorial how to have the node that they are running with the Substrate node template appear at telemetry.polkadot.io by running `./target/release/node-template ... --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'`, and it appears to be up to date as it includes the requirement to specify a telemetry verbosity level, which users can find out about by running `./target/release/node-template --help`
```
        --telemetry-url <URL VERBOSITY>...                       
            The URL of the telemetry server to connect to.
            
            This flag can be passed multiple times as a means to specify multiple telemetry endpoints. Verbosity levels
            range from 0-9, with 0 denoting the least verbosity. Expected format is 'URL VERBOSITY', e.g. `--telemetry-
            url 'wss://foo/bar 0'`.
```
but it seems strange how it shows how to publish nodes of your "private" network at a "public" telemetry link

but i think what's missing is:
1) a dedicated section at https://substrate.dev/ that explains Substrate Telemetry, that mentions the following (then provide links to that dedicated section from the different links that use telemetry):
  * what the key code repos are that have incorporated the option `--telemetry-url` and scenarios why people might find it useful to use the option, or when they shouldn't use it perhaps for security reasons
    * https://github.com/paritytech/substrate-telemetry
    * https://github.com/substrate-developer-hub/substrate-node-template
    * https://github.com/substrate-developer-hub/substrate-parachain-template
  * how to easily search for a project like "Polkadot" at the public telemetry url to show details of all the nodes connected to it e.g. https://telemetry.polkadot.io/#list/Polkadot
  * perhaps mentioning why the value for option `--telemetry-url` was changed to `wss://telemetry.polkadot.io/submit/` whereas a long time ago it was `wss://telemetry.polkadot.io:1024` 
  * mention what the telemetry url verbosity `--telemetry-url '<URL> <VERBOSITY>'` means and why you'd use it (e.g. '--telemetry-url ws://telemetry.polkadot.io:1024 0'
  * mention whether it matters if you specify `ws://` or `wss://` for the telemetry url, since for example `ws://` is used [here](https://github.com/paritytech/substrate-telemetry#terminal-3---node), but `wss://` is used [here](https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain#first-participant-starts-a-bootnode)
2) update this section https://github.com/paritytech/substrate-telemetry#terminal-3---node, as it looks outdated, as it doesn't specify the telemetry verbosity in the url (e.g. `polkadot --dev --telemetry-url 'wss://localhost:8000/submit 0'), but in any case, i think this section should show how to connect the substrate-node-template to it instead (e.g. `./target/release/node-template --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0'` and link to https://github.com/ltfschoen/substrate-node-template instead

**Comment by chevdor** [comment]
Hey Luke (@ltfschoen), 
It looks like you have a sharp idea of what should be done and where. Do you want to open some PRs in the appropriate repos ?

As a side note, we all know that software (and urls) get updated. This is why I am a believer that information should be duplicated as little as possible, otherwise it becomes out of date and hard to maintain everywhere.

The primary source of information should be [this repo](https://github.com/paritytech/substrate-telemetry) and obviously, it cannot cover all the cases but it should explain the general idea and the options.
IMO, instead a every repo documenting telemetry, they should (and usually do) give one example and point to the [substrate-telemetry repo](https://github.com/paritytech/substrate-telemetry) for more info. This is the best to easily keep things up to date.

So let me take your list:

> a dedicated section at https://substrate.dev/ that explains Substrate Telemetry, that mentions the following (then provide links to that dedicated section from the different links that use telemetry) 

- [ ] Since this is a suggestion for [another repo](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io) I would suggest to open an issue or better a PR there and link it here if you like

> what the key code repos are that have incorporated the option --telemetry-url and scenarios why people might find it useful to use the option, or when they shouldn't use it perhaps for security reasons

not impossible for this repo to track all projects but hard to actually discover and keep track of them all. In general all substrate chains will support telemetry unless it has been removed specifically. So if every project using telemetry sets appropriate [github topics](https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/classifying-your-repository-with-topics) such as `substrate`, it would help discovery thanks to [such a link](https://github.com/search?q=substrate) 

> how to easily search for a project like "Polkadot" at the public telemetry url to show details of all the nodes connected to it e.g. https://telemetry.polkadot.io/#list/Polkadot

Not sure I understand whether this is a question of a suggestion. Can you explain ?

> perhaps mentioning why the value for option --telemetry-url was changed to wss://telemetry.polkadot.io/submit/ whereas a long time ago it was wss://telemetry.polkadot.io:1024

Why would we want to keep track of old stuff (that would be a lot of useless information...). The documentation should be actual and reflect the current state. If you see old values in a repo, the best is to open an issue in such a repo and mention it. Did you see outdated values in this repo?

> mention what the telemetry url verbosity --telemetry-url '<URL> <VERBOSITY>' means and why you'd use it (e.g. '--telemetry-url ws://telemetry.polkadot.io:1024 0'

Fair point, I created https://github.com/paritytech/substrate-telemetry/issues/357 for that.

> mention whether it matters if you specify ws:// or wss:// for the telemetry url, since for example ws:// is used here, but wss:// is used here

I would argue with that. When using a custom endpoint, the user should know what is the url and use the right one. ws:// and wss:// are not the same and cannot be swapped. `ws://` vs `wss://` is similar to `http://` vs `https://` and the `s` stand for `SSL` certificate. 
Some repos will mention `wss://` (usually pointing at official telemetry backends) while some other repo/examples will mention only `ws://` for local telemetry backend where the user/documenter does not want to go into setting up ssl certificates (which brings nothing for testing only).

> update this section ...

Linked in https://github.com/paritytech/substrate-telemetry/issues/357. Since you have the answer, you may consider make a PR directly :)

**Comment by ltfschoen** [comment]
> Do you want to open some PRs in the appropriate repos ?
i'd rather just comment about it for the moment here. if we can get someone who's an owner/maintainer of the other repos or in charge of substrate.dev to comment in this thread that they'd be in favour of a PR being created then i'd invest time doing it. i just think it would be of value to add a Telemetry section to substrate.dev, but others may not agree.

> I am a believer that information should be duplicated as little as possible, otherwise it becomes out of date and hard to maintain everywhere
agreed!


> how to easily search for a project like "Polkadot" at the public telemetry url to show details of all the nodes connected to it e.g. https://telemetry.polkadot.io/#list/Polkadot

  > Not sure I understand whether this is a question of a suggestion. Can you explain ?

this was just a suggestion of what could be included if there was a dedicated Telemetry section in the docs at substrate.dev


> Why would we want to keep track of old stuff (that would be a lot of useless information...). The documentation should be actual and reflect the current state. If you see old values in a repo, the best is to open an issue in such a repo and mention it. Did you see outdated values in this repo?

agreed, not necessary to say why they're no longer using the post 1024

> Fair point, I created #357 for that.

good work!

> Some repos will mention wss:// (usually pointing at official telemetry backends) while some other repo/examples will mention only ws:// for local telemetry backend where the user/documenter does not want to go into setting up ssl certificates (which brings nothing for testing only).

no objections

> Linked in #357. Since you have the answer, you may consider make a PR directly :)

ok i've made a PR here https://github.com/paritytech/substrate-telemetry/pull/358

**Comment by chevdor** [comment]
Nice, thanks !
So I think we can close this issue and track the rest at:
- https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/948
- #357 
- #358
