### ISSUE TITLE
Support for X-Real-IP or something in geolocation

### ISSUE THREAD

**Issue by burner1024** [paritytech/substrate-telemetry#389]
When run through docker-compose, communication is plain text. I set up Nginx to proxy with ssl, but now geolocation sees docker local ip instead of node ips, and consequently fails to locate them with ipapi.co.

**Comment by jsdw** [comment]
Geolocation should already make use of several headers where available (the standard `Forwarded` header, then `X-Forwarded-For`, then `X-Real-Ip`).

One way that I've tested this manually in the past is to use the excellent `websocat` tool to "connect" a node, and test one of the forwarded headers:

```
echo '{"id":1,"ts":"2021-07-12T10:37:47.714666+01:00","payload":{"authority":true,"chain":"Local Testnet","config":"","genesis_hash":"0x1122334455667788990011223344556677889900112233445566778899001122","implementation":"Substrate Node","msg":"system.connected","name":"Alice","network_id":"12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp","startup_time":"1625565542717","version":"2.0.0-07a1af348-aarch64-macos"}}' \
	| websocat ws://localhost:8001/submit -H 'X-Real-Ip: 8.8.8.8' -n
```

It may be that Nginx needs configuring to add the header itself as needed, or that the node IP is an internal network address (note that a special exception is made for 127.0.0.1 just for dev purposes) which is why it is not working for you.

**Comment by burner1024** [comment]
Cool, I got it working, thank you. (just didn't find this documented anywhere, so I assumed there's no support yet)
